[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/time"
  to = "/.netlify/functions/time"
  status = 200

[[redirects]]
  from = "/set-promo"
  to = "/.netlify/functions/set-promo"
  status = 200
