[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/time"
  to = "/.netlify/functions/time"
  status = 200

[[redirects]]
  from = "/set-promo"
  to = "/.netlify/functions/set-promo"
  status = 200

[[redirects]]
  from = "/redeem-promo"
  to = "/.netlify/functions/redeem-promo"
  status = 200

[[redirects]]
  from = "/manage-promos"
  to = "/.netlify/functions/manage-promos"
  status = 200

[[redirects]]
  from = "/scripts/*"
  to = "/404.html"
  status = 404
  force = true
